name: Build HinataBot APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev libgdbm-dev liblzma-dev libreadline-dev libffi-dev libncurses5-dev libncursesw5-dev xz-utils zlib1g-dev ccache zip unzip openjdk-17-jdk

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HinataBot-APK
        path: bin/*.apk
